backend:
  name: github
  branch: main
  repo: nohonature/nohonature
  base_url: https://noho-oauth.plain-mountain-4553.workers.dev
  auth_endpoint: /auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    files:
      - file: "products.html"
        label: "Products Page"
        name: "products"
        fields:
          - { label: "Page Content", name: "body", widget: "text" }
