backend:
  name: github
  branch: main
  repo: NOHONATURE/nohonature
  base_url: https://noho-oauth.plain-mountain-4553.workers.dev
  auth_endpoint: /auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
